export const PRODUCTS = {
    PROD_TMO_5W30: { brand: "Toyota", productName: "TMO 5W-30 SN GF-5", viscosity: "5W-30", api: "SN", acea: "A5/B5", ilsac: "GF-5", baseOil: "Synthetic Blend", group: "Group III", countryOrigin: "Indonesia", tokopedia: "#", shopee: "#", officialStore: "#", price: 400000, priceLevel: "$$", counterfeitRisk: "Sangat Tinggi", performanceScore: 75, valueScore: 85, availabilityScore: 99 },
    PROD_TMO_15W40: { brand: "Toyota", productName: "TMO 15W-40 CI-4", viscosity: "15W-40", api: "CI-4", acea: "E7", ilsac: "N/A", baseOil: "Mineral", group: "Group II", countryOrigin: "Indonesia", tokopedia: "#", shopee: "#", officialStore: "#", price: 380000, priceLevel: "$", counterfeitRisk: "Sangat Tinggi", performanceScore: 70, valueScore: 80, availabilityScore: 99 },
    PROD_HONDA_0W20: { brand: "Honda", productName: "Honda E-Pro Gold 0W-20", viscosity: "0W-20", api: "SN", acea: "A5/B5", ilsac: "GF-5", baseOil: "Fully Synthetic", group: "Group III+", countryOrigin: "Indonesia", tokopedia: "#", shopee: "#", officialStore: "#", price: 500000, priceLevel: "$$$", counterfeitRisk: "Tinggi", performanceScore: 82, valueScore: 78, availabilityScore: 95 },
    PROD_MITSUBISHI_0W20: { brand: "Mitsubishi", productName: "MMGO 0W-20", viscosity: "0W-20", api: "SN", acea: "-", ilsac: "GF-5", baseOil: "Synthetic", group: "Group III", countryOrigin: "Indonesia", tokopedia: "#", shopee: "#", officialStore: "#", price: 450000, priceLevel: "$$", counterfeitRisk: "Sedang", performanceScore: 80, valueScore: 82, availabilityScore: 90 },
    PROD_SHELL_HX7: { brand: "Shell", productName: "Shell Helix HX7 10W-40", viscosity: "10W-40", api: "SN", acea: "A3/B4", ilsac: "N/A", baseOil: "Synthetic Technology", group: "Group III", countryOrigin: "Global", tokopedia: "#", shopee: "#", officialStore: "#", price: 320000, priceLevel: "$", counterfeitRisk: "Tinggi", performanceScore: 78, valueScore: 95, availabilityScore: 98 },
    PROD_SHELL_ULTRA: { brand: "Shell", productName: "Shell Helix Ultra 5W-30", viscosity: "5W-30", api: "SP", acea: "A3/B4", ilsac: "GF-6", baseOil: "PurePlus Technology (GTL)", group: "Group III+", countryOrigin: "Global", tokopedia: "#", shopee: "#", officialStore: "#", price: 750000, priceLevel: "$$$$", counterfeitRisk: "Tinggi", performanceScore: 95, valueScore: 75, availabilityScore: 90 },
    PROD_MOTUL_HTECH: { brand: "Motul", productName: "Motul H-Tech 100 Plus 5W-30", viscosity: "5W-30", api: "SP", acea: "A5/B5", ilsac: "GF-6A", baseOil: "100% Synthetic", group: "Group IV (PAO Blend)", countryOrigin: "Perancis/Vietnam", tokopedia: "#", shopee: "#", officialStore: "#", price: 650000, priceLevel: "$$$", counterfeitRisk: "Sedang", performanceScore: 92, valueScore: 80, availabilityScore: 85 },
    PROD_MOTUL_CRDI: { brand: "Motul", productName: "Motul CRDi Specific 5W-40", viscosity: "5W-40", api: "CF", acea: "A3/B4", ilsac: "N/A", baseOil: "100% Synthetic", group: "Group IV Blend", countryOrigin: "Perancis/Vietnam", tokopedia: "#", shopee: "#", officialStore: "#", price: 700000, priceLevel: "$$$", counterfeitRisk: "Sedang", performanceScore: 94, valueScore: 78, availabilityScore: 80 },
    PROD_LIQUI_MOLY: { brand: "Liqui Moly", productName: "Liqui Moly Molygen 5W-30", viscosity: "5W-30", api: "SP", acea: "A5/B5", ilsac: "GF-6", baseOil: "Synthetic (MFC Technology)", group: "Group III+ with MFC", countryOrigin: "Jerman", tokopedia: "#", shopee: "#", officialStore: "#", price: 950000, priceLevel: "$$$$$", counterfeitRisk: "Rendah", performanceScore: 98, valueScore: 65, availabilityScore: 70 },
    PROD_AMSOIL_0W20: { brand: "Amsoil", productName: "Amsoil Signature Series 0W-20", viscosity: "0W-20", api: "SP", acea: "A1/B1", ilsac: "GF-6A", baseOil: "100% Synthetic PAO", group: "Group IV", countryOrigin: "USA", tokopedia: "#", shopee: "#", officialStore: "#", price: 1100000, priceLevel: "$$$$$", counterfeitRisk: "Sangat Rendah", performanceScore: 99, valueScore: 60, availabilityScore: 65 }
};
